name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Format Python with ruff
        run: |
          source .venv/bin/activate
          ruff check . --fix --unsafe-fixes
          ruff format .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node dependencies
        run: |
          npm install -g prettier markdownlint-cli2

      - name: Format Markdown with prettier
        run: prettier --write "**/*.md"

      - name: Fix Markdown with markdownlint
        run: markdownlint-cli2 --fix "**/*.md"

      - uses: autofix-ci/action@v1